---
rules:
    no-todo: true
    no-start-duplicated-conjunction: true
    max-comma: true
    no-empty-section: true
    no-empty-element: true

    date-weekday-mismatch:
        lang: en-US

    period-in-list-item: true
    period-in-header: true
    footnote-order: true
    doubled-spaces: true
    apostrophe: true

filters:
    comments: true
plugins: [html, latex2e]