---
classic: false

blocks: [permission, user, date, git, name]

color:
    when: auto
    theme: custom
date: +%d %b %y %X
dereference: false
display: almost-all

icons:
    when: auto
    theme: fancy
    separator: ' '
ignore-globs: [.git]
indicators: false
layout: grid

recursion:
    enabled: false
size: default
permission: rwx

sorting:
    column: name
    reverse: false
    dir-grouping: first
no-symlink: false
total-size: false
hyperlink: auto
symlink-arrow: ⇒
header: false