require("interface.alpha")
require("interface.bufferline")
require("interface.dressing")
-- require("interface.image")
-- require("interface.dropbar")
require("interface.lualine")
require("interface.scrollview")
require("interface.transparent")
-- require("interface.satellite")
require("interface.treesitter")
require("interface.treesitter-context")

-- mason must this way to work at boot
require("lsp.mason")
require("lsp.mason-lsp")
require("lsp.mason-tool-installer")

require("lsp.cmp")
require("lsp.lsp")
require("lsp.none-ls")
require("lsp.nvterm")
require("lsp.trouble")

require("schemes.catppuccin")
-- require("schemes.kanagawa")
-- require("schemes.onedark")
-- require("schemes.tokyonight")

require("tools.autopairs")
require("tools.colorizer")
require("tools.comment")
require("tools.gitsigns")
require("tools.harpoon")
require("tools.ibl")
require("tools.markdownpreview")
require("tools.neorg")
require("tools.registers")
require("tools.surround")
require("tools.telescope")
require("tools.telescope-zoxide")
require("tools.tree")
require("tools.undotree")
require("tools.which-key")
